# See https://pre-commit.com/hooks.html for more hooks
# Update hooks with `pre-commit autoupdate`
# Manually run with `pre-commit run --all-files`
repos:
  # Common
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files
      - id: check-case-conflict
  - repo: local
    hooks:
      - id: biome-check
        name: Lint with Biome
        language: system
        entry: npm x -- biome check --write
        pass_filenames: false
  - repo: local
    hooks:
      - id: tsc
        name: Static type check with tsc
        language: system
        entry: npm x -- tsc --noEmit
        pass_filenames: false
